spring:
    profiles: test
    datasource:
        url: ${DB_PMB_TEST_URL}
        username: ${DB_PMB_TEST_USERNAME}
        password: ${DB_PMB_TEST_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate.ddl-auto: create-drop
        generate-ddl: false
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    servlet:
        multipart:
            max-file-size: 8MB
    thymeleaf:
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
server:
    error:
        whitelabel:
            enabled: false